matrix:
    include:
        - language: rust
          cache: cargo
          before_script:
              - curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2 | tar jxf -
              - rustup component add clippy --toolchain stable
          script:
              - cargo build --verbose --all
              - cargo test --verbose --all
              - cargo clippy --verbose --all
              - |
                  zip -0 ccov.zip `find . \( -name "advent-of-code*.gc*" \) -print`;
                  ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
                  bash <(curl -s https://codecov.io/bash) -f lcov.info;
              - mkdir coverage && mkdir coverage/rust
              - mv ./lcov.info ./coverage/rust/lcov.info
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: coverage
              on:
                  branch: master

        - language: node_js
          node_js:
              - 'lts/*'
          cache:
              directories:
                  - node_modules

          before_script:
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build

          script:
              - npm run test:coverage

          after_script:
              - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN
              keep_history: true
              local_dir: coverage
              on:
                  branch: master
after_script:
    - ls coverage
