matrix:
    include:
        - language: node_js
          node_js:
              - 'lts/*'
          cache:
              directories:
                  - node_modules

          before_script:
              - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              - chmod +x ./cc-test-reporter
              - ./cc-test-reporter before-build

          script:
              - npm run test:coverage

          after_script:
              - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

        - language: rust
          rust:
              - stable
              - beta
              - nightly
          matrix:
              allow_failures:
                  - rust: nightly
              fast_finish: true
          script:
              - cargo test --all
