packages:
  - 'solutions/typescript/libs/*'
  - 'solutions/typescript/2015/*'
  - 'solutions/typescript/2016/*'
  - 'solutions/typescript/2017/*'
  - 'solutions/typescript/2018/*'
  - 'solutions/typescript/2019/*'
  - 'solutions/typescript/2020/*'
  - 'solutions/typescript/2021/*'
  - 'solutions/typescript/2022/*'
  - 'solutions/typescript/2023/*'
  - 'solutions/typescript/2024/*'
link-workspace-packages: 'deep'
