[package]
name = "aoc_scaffold"
version = "0.2.0"
authors = ["AlexAegis <alexaegis@gmail.com>"]
license = "mit"
edition = "2018"

[dependencies]
tokio = "*"
aoc_query = { path = "./aoc-query" }
cpt = "0.4.1"
serde = "1.0.103"
serde_json = "1.0.42"
