[package]
name = "scaffold"
version = "0.0.1"
authors = ["AlexAegis <alexaegis@gmail.com>"]
license = "mit"
edition = "2018"

[dependencies]
clap = "*"
async-std = "*"

[dev-dependencies]
criterion = "*"
