[package]
name = "aoclib"
version = "1.0.0"
authors = ["AlexAegis <alexaegis@gmail.com>"]
license = "mit"
edition = "2018"

[lib]
name = "aoclib"
path = "./src/lib.rs"

[dependencies]
aoc = { path = "../../../" }
num-traits = "*"
