[package]
name = "mirror_folder"
version = "0.1.0"
authors = ["AlexAegis <alexaegis@gmail.com>"]
license = "mit"
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.6"
clap = "*"
walkdir = "*"
async-std = "*"
serde = "*"
handlebars = "3.0.0-beta.1"
