name: Python

on:
  push:
    paths:
      - 'solutions/python/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'solutions/python/**'
      - '.github/workflows/python.yml'

defaults:
  run:
    working-directory: solutions/python

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    env:
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: solutions/python/.venv3
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install venv
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: pipenv install
      - name: Lint
        run: pipenv run lint
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    env:
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install venv
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: pipenv install
      - name: Format check
        run: pipenv run fmt
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']
    env:
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install venv
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: pipenv install
      - name: Test
        run: pipenv run test
