name: Python

on:
  push:
    paths:
      - 'solutions/python/**'
  pull_request:
    paths:
      - 'solutions/python/**'

defaults:
  run:
    working-directory: solutions/python

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
