name: Python

on:
  push:
    paths:
      - 'solutions/python/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'solutions/python/**'
      - '.github/workflows/python.yml'

defaults:
  run:
    working-directory: solutions/python

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2
        with:
          command: install -d
      - name: Test
        uses: VaultVulp/action-pipenv@v2
        with:
          command: run lint
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2
        with:
          command: install -d
      - name: Test
        uses: VaultVulp/action-pipenv@v2
        with:
          command: run fmt
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Test
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
