name: Python

on:
  push:
    paths-ignore:
      - 'solutions/rust/**'
      - 'solutions/typescript/**'
  pull_request:
    paths-ignore:
      - 'solutions/rust/**'
      - 'solutions/typescript/**'

defaults:
  run:
    working-directory: solutions/python

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: solutions/python/.venv3
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv install -d
      - name: Lint
        run: pipenv run lint
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: solutions/python/.venv3
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv install -d
      - name: Format check
        run: pipenv run fmt
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Cache
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: solutions/python/.venv3
          key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv install -d
      - name: Test
        run: pipenv run test
